version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true
  
install:
#See: https://github.com/appveyor/ci/issues/505
 - ps: |
    $exePath = "$($env:USERPROFILE)\nsis-3.04-setup.exe"
    (New-Object Net.WebClient).DownloadFile('https://downloads.sourceforge.net/project/nsis/NSIS%203/3.04/nsis-3.04-setup.exe', $exePath)
    cmd /c start /wait $exePath /S /D=C:\nsis
build_script:
  gradlew.bat build --info --no-daemon

test_script:
  gradlew.bat test compileSlowtest datatest pfinttest buildDist buildNsis --info --no-daemon

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  
artifacts:
- path: '**/release/*.exe'
  name: PCGen Installer
  
- path: '**/build/distributions/*.zip'
  name: PCGen Zip Distribution

- path: '**/build/distributions/*.tar'
  name: PCGen Tar Distribution
  
matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\.gradle
