version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

install:
 - cmd: |
    choco install gradle nsis
build_script:
  gradle build --info --no-daemon

test_script:
  gradle test compileSlowtest datatest pfinttest buildDist --info --no-daemon

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk11

artifacts:
- path: '**/release/*.exe'
  name: PCGen Installer

- path: '**/build/distributions/*.zip'
  name: PCGen Zip Distribution

- path: '**/build/distributions/*.tar'
  name: PCGen Tar Distribution

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\.gradle
