# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build PCgen full

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        distribution: adopt
        java-version: 16
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build copyToOutput test compileSlowtest datatest pfinttest allReports buildDist
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        distribution: adopt
        java-version: 16
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew all
    - id: getfilename
      run: echo "::set-output name=zip::$(ls build/distributions/*.zip)" && echo "::set-output name=zipname::$(basename build/distributions/*.zip)" && echo "::set-output name=tar::$(ls build/distributions/*.tar)" && echo "::set-output name=tarname::$(basename build/distributions/*.tar)"
    - name: Upload pcgen zip artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ steps.getfilename.outputs.zipname }}
        path: ${{ steps.getfilename.outputs.zip }}
    - name: Upload pcgen tar artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ steps.getfilename.outputs.tarname }}
        path: ${{ steps.getfilename.outputs.tar }}
